### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by dieb** [dieb/spotify-lyrics#3]
Depends on #2

**Comment by brenopolanski** [comment]
+1

Does not work on Linux (Ubuntu 14.04).

![screenshot from 2016-12-15 14-35-11](https://cloud.githubusercontent.com/assets/1894191/21235036/e00f7f30-c2d3-11e6-8545-6b192f888935.png)

**Comment by dieb** [comment]
I think fixing issue #2 should get it working.

I also noticed that the title font looks bad. Is it something on the screenshot or does it actually look bad? If so, I think it's worth opening an issue. It might just be some antialiasing CSS config

**Comment by brenopolanski** [comment]
well.. does actually look bad.

![screenshot from 2016-12-15 17-23-30](https://cloud.githubusercontent.com/assets/1894191/21240738/571854d2-c2eb-11e6-9ccf-193bff2fc0d7.png)

**Comment by dieb** [comment]
@brenopolanski could you please give it another try?

**Comment by brenopolanski** [comment]
@dieb the app not worked.

I have this error in my terminal:

```
# npm run app                

> spotify-lyrics@1.1.0 app /home/brenopolanski/github/PR/spotify-lyrics
> electron app


(electron:10881): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(electron:10881): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(electron:10881): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(electron:10881): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

![screenshot from 2016-12-17 14-42-38](https://cloud.githubusercontent.com/assets/1894191/21288651/8b5a03bc-c467-11e6-8b5a-defbc8c8801f.png)

**Comment by dieb** [comment]
Interesting. I'm on elementaryOS and it works. Are you on Ubuntu?

It'd be really helpful if you could send me the output of dbus-monitor for about 10 seconds while you play different songs on spotify (you can hit play on 4 of them in a row)

**Comment by dieb** [comment]
Tested and works on elementaryOS and Arch Linux. Closing until we get further evidence of breakage 💃

**Comment by brenopolanski** [comment]
@dieb sorry for my delay...

well... now i have a screen black, when run `spotify-lyrics`.

![screenshot from 2016-12-21 12-08-51](https://cloud.githubusercontent.com/assets/1894191/21394488/93acca32-c777-11e6-8ace-4bcefcda546e.png)

I too have a output of dbus-monitor. See below:

http://pastebin.com/S3sAeByC
